services:
  app:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite:/app/db.sqlite
    ports:
      - "5000:5000"
    depends_on:
      - frontend

  frontend:
    image: httpd:latest
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
      - "3000:80"